### ISSUE TITLE
MetricReplace find and replace on the node hostname too

### ISSUE THREAD

**Issue by daks** [MattHodge/Graphite-PowerShell-Functions#37]
I'm trying v1.2.0 of the module, with an explicit NodeHostName (I need the FQDN hostname) like

    <NodeHostName>host_domain_tld</NodeHostName>

When the script send metrics to Graphite, it does find and replace on the node hostname which is not the intended behaviour, so my hostname become **hostdomaintld** (because of the default rule finding "_").

**Comment by MattHodge** [comment]
Fixed in [Graphite-PowerShell v1.2.1](https://github.com/MattHodge/Graphite-PowerShell-Functions/releases/tag/v1.2.1).

Thanks for reporting the issue!

**Comment by MattHodge** [comment]
v1.2.1 had a bug, please grab [Graphite-PowerShell v1.2.2](https://github.com/MattHodge/Graphite-PowerShell-Functions/releases/tag/v1.2.2) instead.
