### ISSUE TITLE
"dot" in counter title

### ISSUE THREAD

**Issue by krjensen** [MattHodge/Graphite-PowerShell-Functions#43]
Hi,

I have a IIS server, where my websites is named "www.siteX.com". When i send this to graphite, it will be showed like this "webservices>www>siteX>com" but i would like do replace the dot in the counter name with "-" so it will end up in graphite like this "webservices>www-siteX-com"

Kristian

**Comment by krjensen** [comment]
This can be fixed by replacing "." with "-" in the original sample path in "Start-StatsToGraphite.ps1."

$sample.path = $sample.path.replace(".","-")

**Comment by MattHodge** [comment]
@krjensen Rather than modifying the scripts, use the configuration files `<MetricCleaning>` options. Readme here: https://github.com/MattHodge/Graphite-PowerShell-Functions#metricreplace-configuration-section

**Comment by krjensen** [comment]
@MattHodge I'm using the config file for many things, but this is not doable using that.

My perfconuter is returning website, and this list kan change from day to day, so i cant hardcode all websites in the config file, i need the script to allow a counter with a "." in the path.
