### ISSUE TITLE
Issues with InfluxDB's Carbon plugin

### ISSUE THREAD

**Issue by nsymms** [MattHodge/Graphite-PowerShell-Functions#46]
Not necessarily an issue with this module, more of a usability issue and something you may want to document on the Readme page...

InfluxDB provides a carbon plugin which is supposed to be 100% compatible with Graphite's Carbon aggregator, but there is a problem. For bulk metric submitting, InfluxDB does not like the use of "\`r" (carriage return) as a delimiter between metrics. You have to use "\`n" (newline).

Single metric submits using Send-GraphiteMetric() worked okay for me, but not Send-BulkGraphiteMetrics(). I had to modify the code in Internal.ps1 (SendMetrics function) to use newline as mentioned above.

If Graphite Carbon can handle newlines instead of carriage returns, it might be prudent to simply switch to using that character. If Graphite does NOT work well with newlines, then a documentation note would be helpful for others who might come across this issue.

**Comment by MattHodge** [comment]
Thanks @nsymms - Have tested Graphite with `n and it was fine.
