### ISSUE TITLE
There are no SQL Servers in your configuration file. No SQL metrics will be collected.

### ISSUE THREAD

**Issue by rjunified** [MattHodge/Graphite-PowerShell-Functions#49]
I am obviously being a complete fool, but I when I try and collect SQL stats I just get the error "There are no SQL Servers in your configuration file. No SQL metrics will be collected."

I have tweaked the below lines with my SQL details

		<SQLServers>
			
			<SQLServer ServerInstance="MYSERVERNAME" Username="mysauser" Password="PASSWORD1!">

and I have edited the query.

What am I doing wrong?

Thanks

**Comment by kasperbrandenburg** [comment]
Did you start the Start-SQLStatsToGraphite function? I've fixed some bugs in the code regarding parsing the SQL Server objects in the config file. Try my branch (still waiting on feedback from project maintainer)
https://github.com/kasperbrandenburg/Graphite-PowerShell-Functions/tree/Fix-SQLMetricCollector-AddMultirowSupport

**Comment by rjunified** [comment]
hi, wow thanks for the quick reply. When i try and run it that is when i get the error

PS C:\Windows\system32> Start-SQLStatsToGraphite -testmode
WARNING: There are no SQL Servers in your configuration file. No SQL metrics will be collected.

How does it know that I have entered the SQL details and it is not just the sample details in there? Is there a flag or something that I need to change to enable the SQL bit?

I am trying to run this from a remote box to query the SQL server remotely I assume that doesnt matter. Appreciate your help.

Rob

**Comment by kasperbrandenburg** [comment]
Hi, did you try my branch? Please dump your SQLServer sections (remove password) and try using -Verbose or set Verbose TRUE in config file to get more output. I'm pretty sure i faced the same issue using Matts branch.

**Comment by rjunified** [comment]
yeah just tried your branch but didnt seem to make any difference, I initially just edited the first few lines but I have stripped the lines I wasnt using in this test so it is now just

	<MSSQLMetics>
		<MetricPath>Parent.Child.SQL</MetricPath>
		<MetricSendIntervalSeconds>120</MetricSendIntervalSeconds>
		<SQLConnectionTimeoutSeconds>5</SQLConnectionTimeoutSeconds>
		<SQLQueryTimeoutSeconds>5</SQLQueryTimeoutSeconds>
		<SQLServers>
			
			<SQLServer ServerInstance="S-2K8-SS02\MSSQLSERVER" Username="username" Password="password">
				<Query Database="EDDS" MetricName="edds.activeusercount" TSQL="SELECT COUNT ([UserID]) FROM [EDDS].[eddsdbo].[UserStatus]"/>
			</SQLServer>
		</SQLServers>
	</MSSQLMetics>


Thanks again

Rob

**Comment by kasperbrandenburg** [comment]
In my branch i've added an extra attribute to the <Query> element, so that might brake later, since that missing from your Config.

Here an example of mine

	<MSSQLMetics>
		<MetricPath>collectd.ops.servers.sqlservers</MetricPath>
		<MetricSendIntervalSeconds>300</MetricSendIntervalSeconds>
		<SQLConnectionTimeoutSeconds>60</SQLConnectionTimeoutSeconds>
		<SQLQueryTimeoutSeconds>60</SQLQueryTimeoutSeconds>
		<SQLServers>
			
			<SQLServer ServerInstance="<database-server>" Username="<user>" Password="<password>">
				
				<Query Database="SiteOps" MetricType="MultiRow" MetricName="" TSQL="EXEC sp_Get_ServerMonitor_DatabaseCpuPerformance @MetricBase = '<database-server>'"/>
				<Query Database="SiteOps" MetricType="MultiRow" MetricName="" TSQL="EXEC sp_Get_ServerMonitor_DatabaseBufferPoolUsage @MetricBase = '<database-server>'"/>
				<Query Database="SiteOps" MetricType="MultiRow" MetricName="" TSQL="EXEC sp_Get_ServerMonitor_SqlServerWaitStats @MetricBase = '<database-server>'"/>
				<Query Database="SiteOps" MetricType="MultiRow" MetricName="" TSQL="EXEC sp_Get_ServerMonitor_SqlServerPerformanceCounters @MetricBase = '<database-server>'"/>
				<Query Database="SiteOps" MetricType="MultiRow" MetricName="" TSQL="EXEC sp_Get_ServerMonitor_SqlServerMemoryClerks @MetricBase = '<database-server>'"/>
				<Query Database="SiteOps" MetricType="MultiRow" MetricName="" TSQL="EXEC sp_Get_ServerMonitor_DatabaseDiskPerformance @MetricBase = '<database-server>'"/>
			</SQLServer>
		</SQLServers>
	</MSSQLMetics>

Did you start by importing the module?
I've put mine in C:\Windows\System32\WindowsPowerShell\v1.0\Modules\ in a Graphite-Powershell folder, and i Import the module before i run the function.

I dont know if what would make a difference in all cases. Give it a try. The Config path is configured through loading the module into your powershell session. But newer versions of PS should do the automatically if the module is placed in the powershell path.

Import-Module Graphite-Powershell
Start-SQLStatsToGraphite

**Comment by rjunified** [comment]
thanks will give it a try with all your stuff, will also try it on one of the dev sql boxes itself, see if that makes a difference. Will report back. Thanks for your help.

Rob

**Comment by kasperbrandenburg** [comment]
alright, happy debug.

**Comment by rjunified** [comment]
hi kasperbrandenburg, me again.

so good news, Its alive using your branch wooohoooo!

Although, if I use the multirow query it seems to ignore the "MetricName" set in the query line and just use the row names returned by the query itself, is this how yours is working?

Thanks again

Rob

**Comment by kasperbrandenburg** [comment]
Hi Rob

Great news that its working. Yes... MetricName is the first column of data, and the value is the second column. This is as i intended. It gives the freedom to fabricate multiple metrics in a single query. You you'd rather use Matts, just set the MetricType="SingleRow" and define the MetricName.. then it will use the MetricName attribute.

**Comment by rjunified** [comment]
Hi, thanks again for replying. Sorry for the delay I have been away from a computer. 
My query is actually a multi row query so good thing i was using your branch. I have multiple multi row queries though and i wanted different sub folders for them at the level above the metric

I modified the multi row bit in the function instead to add the metric name and then the multi row values. All good now. Thanks so much!

My multirow build metric looks like:

$metricPath = $Config.MSSQLMetricPath + '.' + $query.MetricName + '.' + $sqlresult[0]
