### ISSUE TITLE
How to get % Physical used Memory with Graphite-PowerShell ?

### ISSUE THREAD

**Issue by toni-moreno** [MattHodge/Graphite-PowerShell-Functions#53]
Hi @MattHodge . I'm working with this wonderful tool and we are getting these memory counters.

```
		<Counter Name="\Memory\Available MBytes" /> 
		<Counter Name="\Memory\Pages/sec" />
		<Counter Name="\Memory\Pages Input/sec" /> 
```
But we also need the % physical used memory . In this case we can  compute the value if either of those values could be obtained.

* % physical used memory.
* % physical Available memory. 
* Total amount of physical Memory  in  Mb/Kb/Bytes.
* used amount phisical memory  Mb/Kb/Bytes

There is any counter matching these values?
There any workaround to get these values from other scripts like perhaps this other( https://github.com/pdxcat/PowerShell-Graphite/blob/master/Get-MemStats.ps1)

**Comment by kkzinger** [comment]
Hi, you can lookup all counters with `(Get-Counter -ListSet *).paths`
And to get some Value from it to evaluate use this `get-counter "\Memory\% Committed Bytes In Use" -SampleInterval 2`
