### ISSUE TITLE
[Feature Request] improve log counter name when counter not found.

### ISSUE THREAD

**Issue by toni-moreno** [MattHodge/Graphite-PowerShell-Functions#58]
While doing some installations there were some errors trying to get some counters. ( After commenting all  counters on the config.xml file we realized that the problem was missing PhisicalDisk counters)

Here the output:

```
Get-Counter : Internal performance counter API call failed. Error: c0000bb8.
At C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Graphite-PowerShell\Funct
ions\Start-StatsToGraphite.ps1:119 char:28
+             $collections = Get-Counter -Counter $Config.Counters 
-SampleInterval ...
```

As you can see the output is not reporting the counter name, would be easier if the output could print the counter name 

Thank you very much

**Comment by MattHodge** [comment]
I'd start looking at Telegraf, which provides a much nice way to send metrics than my PowerShell function: https://hodgkins.io/windows-metric-dashboards-with-influxdb-and-grafana
