### ISSUE TITLE
Memory continuously increase

### ISSUE THREAD

**Issue by gbrian** [MattHodge/Graphite-PowerShell-Functions#61]
Hi there,

Our current **StatsToGraphite** service continuously increases its memory consume during the day having to restart it daily.
We are have the scripts installed as a service using NSSM. 
Any idea about why is this happening ? 

Thanks

**Comment by MattHodge** [comment]
I'd start looking at Telegraf, which provides a much nice way to send metrics than my PowerShell function: https://hodgkins.io/windows-metric-dashboards-with-influxdb-and-grafana
